swagger: "2.0"
info:
  description: "API"
  version: "1.0.0"
  title: "API"
  termsOfService: "http://api.io/terms/"
  contact:
    email: "dev@api.io"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "api.io"
basePath: "/api/v1"
schemes:
- "http"
paths:
  /:
    get:
      summary: "Welcome"
      description: "Welcome"
      operationId: "welcome"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Message"
definitions:
  Message:
    type: "object"
    properties:
      message:
        type: "string"
